### ISSUE TITLE
Random fox sometimes results in 413 REQUEST ENTITY TOO LARGE

### ISSUE THREAD

**Issue by synrg** [tmercswims/tmerc-cogs#106]
**Cog in question**

randimals

**Describe the bug**

When using the `fox` command, sometimes the random fox is too large and the user sees a generic error message:

`Error in command 'fox'. Check your console or logs for details.`

**To Reproduce**

Unfortunately, since the images are random, it's hard to come up with a reproducible case.

**Expected behavior**

We expected to see a fox image.

**Additional context**

Traceback:

```
[2020-01-13 19:02:14] [ERROR] red: Exception in command 'fox'
Traceback (most recent call last):
  File "/home/synrg/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/synrg/.local/share/Dumbo/cogs/CogManager/cogs/randimals/randimals.py", line 76, in fox
    await ctx.send(file=discord.File(io.BytesIO(await image.read()), filename=filename))
  File "/home/synrg/.local/lib/python3.8/site-packages/redbot/core/commands/context.py", line 82, in send
    return await super().send(content=content, **kwargs)
  File "/home/synrg/.local/lib/python3.8/site-packages/discord/abc.py", line 805, in send
    data = await state.http.send_files(channel.id, files=[file],
  File "/home/synrg/.local/lib/python3.8/site-packages/discord/http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 413 REQUEST ENTITY TOO LARGE (error code: 40005): Request entity too large
```

**Comment by tmercswims** [comment]
Great catch! It seems there is [one image](https://wohlsoft.ru/images/foxybot/foxes/q3hq3h4wqycvwjhw4j6.gif) that the fox API can give back which is a 60MB gif, and is the cause of this issue.

It forced me to rewrite a lot of this cog to handle failures better, so thank you very much for reporting it!

**Comment by tmercswims** [comment]
0f2739f5870fe0f370df5e084d83ebce02aabb58 should address the problem. If you run into it again, do let me know!
