### ISSUE TITLE
Rainbow6siege error

### ISSUE THREAD

**Issue by Tiago0** [tmercswims/tmerc-cogs#69]
Hello, i'm getting error on any kinda of command i try to use:

Exception in command 'r6s profile'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/cogs/rainbow6siege.py", line 117, in _profile
    p = await self.get_player(player, platform)
  File "/cogs/rainbow6siege.py", line 59, in get_player
    ).get_player(player, plat)
  File "lib/r6sapi/r6sapi.py", line 441, in get_player
    results = yield from self.get_players(term, platform)
  File "lib/r6sapi/r6sapi.py", line 413, in get_players
    data = yield from self.get("https://public-ubiservices.ubi.com/v2/profiles?nameOnPlatform=%s&platformType=%s" % (parse.quote(term), parse.quote(platform)))
  File "lib/r6sapi/r6sapi.py", line 374, in get
    yield from self.connect()
  File "lib/r6sapi/r6sapi.py", line 351, in connect
    raise FailedToConnect
r6sapi.r6sapi.FailedToConnect

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 634, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "lib/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FailedToConnect:

**Comment by tmercswims** [comment]
The error seems to indicate that the credentials you set with `[p]r6sset credentials <email> <password>` are incorrect. And if I purposefully set bad credentials, I get this error also, so I'm fairly sure that's what it is.

I will add better handling of this error, but for now, verify that your credentials are correct, and then try again.

**Comment by Tiago0** [comment]
That's it, after my dumbness i setup with the right password and now is working fine.

Thank you for your help and awesome work!
